In [2]:
import numpy
n=numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
type(n)

numpy.ndarray

In [5]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
m=numpy.asarray([[123,12,123,12,33],[],[]],dtype=object)

In [8]:
type(m)

numpy.ndarray

In [10]:
print(m)

[list([123, 12, 123, 12, 33]) list([]) list([])]


In [11]:
import cv2

In [12]:
img1=cv2.imread("smallgray.png",0)
img1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [13]:
img2=cv2.imread("smallgray.png",1)
img2

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [14]:
cv2.imwrite("newsmallgray.png",img2)

True

In [15]:
cv2.imwrite("newsmallbnw.png",img1)

True

In [16]:
img1[0,2]

104

In [17]:
img1[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [18]:
img1[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [21]:
img1.shape

(3, 5)

In [23]:
for i in img1:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [24]:
for i in img1.T:
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [25]:
for i in img1.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [28]:
ims=numpy.hstack((img1,img1))

In [29]:
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [31]:
ims1=numpy.vstack((img1,img1,img1))
ims1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [34]:
lst=numpy.hsplit(ims1,5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [35]:
lst1 = numpy.vsplit(img1,3)
lst1

[array([[187, 158, 104, 121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182]], dtype=uint8)]